services:
  # Backend Service
  - type: web
    name: shiftwise-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: |
      gunicorn shiftwise_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: shiftwise-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: shiftwise-db
          property: connectionString
    healthCheckPath: /api/health/
    plan: free

  # Frontend Service
  - type: web
    name: shiftwise-frontend
    env: node
    buildCommand: |
      cd Shedular@@
      npm install
      npm run build
    startCommand: |
      cd Shedular@@
      npm start
    envVars:
      - key: VITE_BACKEND_URL
        value: https://shiftwise-backend.onrender.com
    healthCheckPath: /
    plan: free

databases:
  - name: shiftwise-db
    databaseName: shiftwise
    user: shiftwise
    plan: free 