services:
  # Backend Service
  - type: web
    name: shiftwise-2
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src/backend
      gunicorn --chdir /opt/render/project/src/backend shiftwise_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: shiftwise-2.onrender.com,shiftwise-1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: shiftwise-db-test
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: shiftwise_backend.settings
    healthCheckPath: /api/health/
    plan: free

  # Frontend Service
  - type: web
    name: shiftwise-1
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: VITE_BACKEND_URL
        value: https://shiftwise-2.onrender.com
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
    plan: free

databases:
  - name: shiftwise-db-test
    databaseName: shiftwise_test
    user: shiftwise_test
    plan: free 