# Generated by Django 4.2.19 on 2025-03-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0003_alter_shift_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
                ('partner_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='shifts.shift')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requester_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='CoverUpShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Claimed'), ('X', 'Cancelled')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverup_claimed', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverup_posted', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverup_shifts', to='shifts.shift')),
            ],
        ),
    ]
