# Generated by Django 4.2.19 on 2025-03-14 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='shift_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('employee', 'shift_date', 'shift_time', 'location')},
        ),
    ]
