# Generated by Django 4.2.19 on 2025-03-17 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='title',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='sender',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
