# Generated by Django 4.2.19 on 2025-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('employee_confirmed', 'Employee Confirmed'), ('confirmed', 'Admin Confirmed'), ('cancelled', 'Cancelled'), ('NULL', 'NULL')], default='pending', max_length=20),
        ),
    ]
